---
kind: pipeline
name: default

steps:
- name: package
  image: harbor.dsrd.libraries.psu.edu/public/helm-push
  environment:
    HELM_PASSWORD:
      from_secret: HELM_PASSWORD
  commands:
  - helm package . --version $DRONE_TAG
  when:
    event: [ tags ]
---
kind: signature
hmac: d0aec8377a8105396c594bb2ca3f1f5031918f05bf18325d7e9b5ed0478e1f03

...
